# Generated by Django 4.1.6 on 2023-02-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
